### ISSUE TITLE
Class is missing Function in prototype chain

### ISSUE THREAD

**Issue by snystedt** [vercel/edge-runtime#89] opened 2022-08-14 05:18 UTC
The following fails in the edge runtime (but not in the node runtime)

```typescript
class Foo {
    constructor() {
        ...
    }
    ...
}

const cls = Foo;
cls instanceof Function // true in node runtime, false in edge runtime
```

Encountered when using the Firebase Client SDK while initializing the auth module where it tries to discern if a passed argument is a class or not.

**Comment by snystedt** [comment] 2022-08-18 08:57
It seems all prototypes are broken. Just tried this now,

```typescript
console.log(Object.prototype)
``` 
prints `[Object: null prototype] {}` in Node, while the edge runtime returns just the empty object, `{}`

**Comment by Kikobeats** [comment] 2022-11-02 12:43
Hello @snystedt, can you add a reproduction of the issue?

It isn't clear it's related to Edge Runtime:

```bash
$ edge-runtime
ƒ => class Foo {}
ƒ => const cls = Foo
ƒ => const result = cls instanceof Function
ƒ => console.log(result)
true
```

is this a thing you are experiencing after deploy a Next.js project or a middleware via Vercel CLI?

**Comment by Kikobeats** [comment] 2022-11-08 17:22
I close it due to lack of information for now

**Closed by Kikobeats** 2022-11-08 17:22 UTC
Labels: bug
